[package]
name = "zoros"
version = "0.1.0"
authors = ["Yogesh Choudhary <yogesum@gmail.com>"]

[dependencies]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[package.metadata.bootimage]
default-target = "x86_64-zoros.json"
